### ISSUE TITLE
Repacker.exe

### ISSUE THREAD

**Issue by armm77** [Marforius/Marforius-Client#1]
The repacker is detected as a malware.
Antivirus Avast.

**Comment by Marforius** [comment]
Yeah I left a note about that in the readme.

Last time I tried to run it I couldn't even figure out how I got it to work last, and gave up on it, luckily I had a backup on a hard drive sitting in another computer, I haven't been in contact with the private server 'scene', or really had the drive or reason to revisit any of this stuff. Just leave the project on watch, and the next time I change anything i'll drop a link in to a torrent that will have the modified executable/data files all prepackaged and ready for use.
